version: '3.3'

services:
        api:
            container_name: guruyu_api
            image: skayear/guruyu_api:latest
            restart: always
            ports:
                - 5000:5000
            volumes:
                - /app
            command: dotnet ./Api.dll

        postgres:
          container_name: postgres_dev
          image: postgres:12 
          restart: always
          ports:
           - 5432:5432
          volumes: 
            - ./dbfiles:/docker-entrypoint-initdb.d
            - /var/lib/postgres_data_prep:/var/lib/postgresql/data
          environment:
            POSTGRES_PASSWORD: guruyu1234
            POSTGRES_USER: GuruyuLiga
            POSTGRES_DB: GuruyuDb
          networks:     
            - dev_guruyu

networks:
  dev_guruyu:
    driver: bridge

        # adminer:
        #   image: adminer
        #   restart: always
        #   ports:
        #     - 54321:54321